---
- name: Install Docker and Run Nginx on EC2
  hosts: webservers
  become: yes

  tasks:
    - name: Install Docker using default package manager (Amazon Linux / RHEL)
      package:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled at boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull latest nginx Docker image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Run nginx container on port 80
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

